### PR TITLE
/usr/bin/env bash

### PR DESCRIPTION
**Pull request by tomberek**
Increases compatibility

### CODE REVIEW

**Comment by marcb** [comment]
This change is needed for NixOS as there is no `/bin/bash`.

e.g.
```bash
$ ls -l `which bash`
lrwxrwxrwx 1 root root 77 Jan  1  1970 /run/current-system/sw/bin/bash -> /nix/store/lb3hli8d9536g45mndwfwyi6fpny0blh-bash-interactive-4.4-p23/bin/bash
```

There is a `/usr/bin/env`:
```bash
 ls -l /usr/bin/env `which env`
lrwxrwxrwx 1 root root 66 Jan  1  1970 /run/current-system/sw/bin/env -> /nix/store/jcv7h31hb0rvz79il6q4lghs7f7qcqb6-coreutils-8.31/bin/env
lrwxrwxrwx 1 root root 66 Dec 24 18:01 /usr/bin/env -> /nix/store/9v78r3afqy9xn9zwdj9wfys6sk3vc01d-coreutils-8.31/bin/env
```

**Comment by tomberek** [comment]
Note: PRs for NixOS:
https://github.com/NixOS/nixpkgs/pull/76793/files
and an alternate method for home-manager that requires less patching:
https://github.com/tomberek/home-manager/blob/bash-my-aws/init/modules/programs/bash-my-aws.nix

**Comment by mbailey** [comment]
Thanks for raising this @tomberek. A quick search on the topic returned advice that `/usr/bin/env` is better for portability but can introduce security issues if your PATH isn't setup right.

I've seen Ruby developers using tools that put every Rubygem bin/ directory at the start of their $PATH. This could result in users exposing their AWS creds to untrusted code. 

There are often tradeoffs between Security and Convenience and I'd like to ensure I've considered them properly.

**Thoughts/Questions**
- Will `/usr/bin/env bash` will fail on any systems?
- Is there a precedent for projects shipping with `/usr/bin/env bash`?
- NixOS is new to me. Sounds like `/usr/bin/env bash` would be helpful there.
- MacOS ships a very old version of Bash although I'm unaware of any impacts on Bash-my-AWS

**Comment by tomberek** [comment]
Good questions. First off, do not change thing just for NixOS. It's easy to patch. 

Here are some attempts at answers:

- Security: It's possible that PATH can be hijacked, but then again, we're using PATH for sed, tr, awk, grep, jq and awscli and more. Not sure that adding bash to that list is much worse. If the rest of the project had absolute path's (super paranoid), then I'd agree that having bash be the only one as dynamic would be bad. Considering almost every other utility is PATH-driven, meh. 
- Failure: I suspect env is more likely to be in /usr/bin than bash in /bin. But i have no proof or statistics.
- Precedent: Yes, it's fairly common. Eg: https://github.com/sstephenson/bats/blob/master/libexec/bats#L1
- NixOS is fairly unique in that it only has /bin/sh and /usr/bin/env in "normal" locations.  With patching as in my PR, or automatic patching, this shouldn't hinder usage (actually, the assumption of being located at `~/.bash-my-aws` is more of an issue). Again, don't change only for this reason.
- bash-my-aws seems to work fine (limited testing only) on OSX


Other notes:
- https://www.in-ulm.de/~mascheck/various/shebang/#env

**Comment by duncan-bayne** [comment]
My $0.02 - `/bin/bash` isn't present on FreeBSD either.  I've always modified Bash scripts to run on my FreeBSD dev systems by using `/usr/bin/env bash` in the shebang line, and they have subsequently worked on FreeBSD _and_ every Linux distro I've tried.

**Comment by mbailey** [comment]
>     * Security: It's possible that PATH can be hijacked, but then again, we're using PATH for sed, tr, awk, grep, jq and awscli and more. Not sure that adding bash to that list is much worse. If the rest of the project had absolute path's (super paranoid), then I'd agree that having bash be the only one as dynamic would be bad. Considering almost every other utility is PATH-driven, meh.

Well put. I agree.

**Pull request merged**
