### PR TITLE
Provided an easy way to change default location from .bash-my-aws

### PR DESCRIPTION
**Pull request by lucienboland**
Hi.
I prefer to keep files like this not directly in my home directory but in the ~/.config directory.

Others might like the flexibility to do the same.  This PR is an attempt to make this easy for others too.

I also changed the "tee --append" to just "tee -a" since the MacOS tee did not support the "--append".

Big fan of this approach and look forward to writing more command extensions in the future.  Great work!

Cheers
Lucien

### CODE REVIEW

**Comment by mbailey** [comment]
Thanks Lucien.

I support the idea of people being able to deploy BMA to a different location if they want.

I'll need to let this percolate a bit. It increases the number of steps for installation.

I'm inclined to replace the install line with this:
```
git clone https://github.com/bash-my-aws/bash-my-aws.git ${BMA_HOME:-$HOME/.bash-my-aws}
```

People who want to just install copy/paste the line. There's enough of a clue in there for people who want to install somewhere else. The user doesn't need to be explicitly prompted to make a decision about location. I hate getting asked to make decisions about things I don't really care about - one reason I'm not a fan of Subway sandwiches! :-)

What do you think?

**Comment by lucienboland** [comment]
Thanks for the feedback... Agree with your comments.  Will figure out how to make the changes within this thread and then you can ponder their inclusion!!

**Comment by mbailey** [comment]
Hi Lucien, I just noticed from the network tree that you had updated. 

Thanks for updating, merging. :-)

**Review by mbailey — COMMENTED** [review]
:+1:

**Pull request merged**
