### PR TITLE
Add instance ssm

### PR DESCRIPTION
**Pull request by rnhurt**
Rather than going through ssh, I now use SSM sessions to connect to my instances.  bma didn't have this capability and it seemed simple enough, so I added it.  I'm not sure how the tests work but this didn't seem to break anything at least.  😄

### CODE REVIEW

**Comment by mbailey** [comment]
Thanks for your submission! Are you finding it useful?

I've not yet explored ssm to connect before but was curious to try this out.

My initial attempt failed:
```
$ aws ssm start-session --target i-0e90dd7f01483de1e

An error occurred (TargetNotConnected) when calling the StartSession operation: i-0e90dd7f01483de1e is not connected.
```

I did a little digging and found a recommendation to add:
```
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
```

I added this but still got the same error. I also found a post [warning against adding this Role](https://cloudonaut.io/aws-ssm-is-a-trojan-horse-fix-it-now/) for security reasons.

My Saturday night hour is up. I'm still curious and hope to look deeper into SSM in the near future.

**Comment by rnhurt** [comment]
I really, really like SSM and will use it over and above SSH whenever possible.  Yes, there are always trade-offs in security but SSM wins on several accounts:
1. You don't have to poke a hole in your firewall or create a bastion box to connect to EC2 instances in a private VPC
1. You don't have to manage keys - AT ALL!  No more worrying about rotating a key when someone leaves or making sure that they didn't leave a key on an instance somewhere.
1. Every keystroke gets logged to an S3 bucket, which you can put a trigger on and watch traffic in near real-time (if you're super paranoid)

Plus there are several things you can do to limit the "danger" of SSM:
1. AWS has deprecate the `AmazonEC2RoleforSSM` and now recommends using the `AmazonSSMManagedInstanceCore` policy.  It is much more focused and removes most of the issues that article lays out.
1. Using separate AWS accounts for different environments cures most of the other issues the article has with SSM.

The only sticky things with SSM right now are:
1. It doesn't respect the login process and always drops you to a plain shell (sh).  The first thing I do is change to a Bash shell (`sudo su -`).
1. It doesn't really allow you to log in as another user; it's always the "ssm" user.
1. It doesn't really play nice with SSH so handy things like SCP don't work properly (at least I haven't been able to get them to work).

However, I have been using this "instance-ssm" a bit and I really like it.  It makes connecting to instances much easier.  :smile: 

BTW: Thank you for "bam" - the more I use it the more I like it!

**Comment by mbailey** [comment]
I didn't get a chance to look into this again on the weekend but was reminded of it by a story on HN tonight: https://github.com/elpy1/ssh-over-ssm. After reading the README, it wasn't clear to me what benefit it gave over simply running `aws ssm start-session --target $instance_id`, mainly because I'm not fully across `ssm start-session` yet. I should change that.

Do you know the URL of a simple set of steps for me to create an EC2 instance and SSH to it via SSM? My first attempt failed, I'd love a CloudFormation stack and intructions for connecting if one exists.

**Comment by rnhurt** [comment]
The only real difference is convenience.  It's much easier to type `instances Syslog | instance-ssm` than it is to find the instance_id and then type out the whole `start-session` command.  I've been using it for the past couple of weeks and I **love** it!  I used to use the bare `start-session` command but this is so much better.

There really shouldn't be too much work to get SSM working.  Basically, you just have to have an EC2 instance that is running a current version of the SSM agent and has the "AmazonSSMManagedInstanceCore" managed policy attached to the instance profile.  

I haven't really gotten the SSH over SSM stuff working, but I don't really miss it.  In the early days of SSM the session was a little buggy and quite slow so it was better to just SSH into an instance.  However, the only downside to SSM access right now is that the session doesn't respect the login profiles and drops you into a raw sh.

**Comment by mbailey** [comment]
I googled for `AmazonSSMManagedInstanceCore` and didn't find a reference to the policy.

Is there any chance you could drop a cloudformation template into your branch with a policy that works?

**Comment by rnhurt** [comment]
@mbailey I added an "ssm.json" file in the "cloudformation" directory to serve as an example of a working CFN template that you can SSM into using this command:  

    instances TestInstance | instance-ssm

One thing that might have tripped you up in your testing is that the SSM Agent that is installed by default is a bit old and doesn't allow connections.  You can updated the agent by using a UserData section in the CFN template or you can use the Session Manager console in the "Start a session"
section.  Finally, you can use the CLI by running the following command:

    aws ssm send-command --document-name "AWS-UpdateSSMAgent" \
      --targets '[{"Key":"InstanceIds","Values":["i-0b05de82xxxxxx"]}]' \
      --parameters '{"allowDowngrade":["false"]}' \
      --timeout-seconds 3600 --max-concurrency "50" --max-errors "0" --region us-east-1

**Comment by rnhurt** [comment]
I've been using this addition for months and it's worked perfectly.  Is there any hope of getting it merged?  What more can I do to help?

**Comment by mbailey** [comment]
Thanks for raising this again.

I’m time poor at the moment but can give this 30 minutes to examine on the
weekend.

Can you provide a couple of commands that will create the instance from
your cloudformation and then ssh in with ssm?

If it works for me I’ll give it more time to consider security, review
code, etc.

I think I tried it pre Covid and ran out of time before seeing it working.

Thanks,

Mike

**Comment by rnhurt** [comment]
@mbailey 

I updated the template (ssm.json) to make it more complete and easier to test.  It now accepts some parameters and automatically updates the SSM agent.  You'll need a VPC ID and a Subnet ID to proceed.

Create the CFN stack:
```
aws cloudformation create-stack --stack-name SSM-Test --template-body file://ssm.json \
  --capabilities CAPABILITY_IAM \
  --parameters ParameterKey=VpcId,ParameterValue=vpc-????? ParameterKey=SubnetId,ParameterValue=subnet-?????
```

Connect to the instance:
```
instances SSMTestInstance | instance-ssm
```

NOTE: Remember to delete the stack when you get done.  😄

**Comment by mbailey** [comment]
Just had a quick look.

The AMI in the CFN will only work in one region (I don't know which one).
It will also stop working at some point (bitrot).

Would you mind putting in an [SSM reference](https://gliptak.github.io/post/aws_ssm_ami/)?

Something like:
```
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs
    ```

**Comment by rnhurt** [comment]
Wow! I didn't know that AWS provided an SSM parameter type that would dynamically look up values.  Now I have to re-visit my personal templates and rework some things.  :smile: 

I've updated the template with your suggestions and tested it and it seems to work great.  :+1:  

NOTE: This template is using Gravaton2 images/EC2 type which should be cheaper.

**Comment by mbailey** [comment]
Creating the stack now.

Do you use `stack-create`?

**Comment by mbailey** [comment]
OK, it worked! Cool.

This means it can go into the next stage of review for inclusion in BMA.

- usefulness
- security implications - how do we manage who can SSH to what?
- simplicity
- documentation
- coding conventions

You'll appreciate it's a lot of work before something goes in. The benefit is that it's damn solid. 2020 saw virtually no work done on it for most of the year and it hasn't suffered from bitrot.

**Comment by rnhurt** [comment]
I don't use `stack-create` because I wrote my own [CFN template "engine"](https://github.com/KangarooBox/cfn-builder) but it looks pretty neat.  I could definitely use it when I do those one-off stacks (like this).  

As for the instance type, yea "t4g" is pretty new but it really only requires one change in the template, or you can run it in a different region.  Either way, I think "t4g" will probably make it to ap sooner or later.  :smile: 

Oh, I'm not complaining about the level of work or push-back on my contributions.  I use this project (almost) every day and I'm extremely happy that it's as solid as it is.  It takes a lot of work to make something like this and I appreciate your effort.  Thanks for letting me contribute.

NOTE: I think [Gitter](https://gitter.im/) is the closest Git comes to a chat platform.

**Comment by nitrocode** [comment]
Hi. I'm also interested in this. We've been using ssm exclusively for months and this would be helpful.

What are the next steps to getting this merged ?

**Comment by mbailey** [comment]
Thanks. This is great.

**Pull request merged**
