### PR TITLE
Add ELBv2 target groups functions

### PR DESCRIPTION
**Pull request by barlik**
I've started using bash-my-aws recently and missed a way to show instances behind application and network load balancers. I created new functions, but then I've noticed an opened pull request #288 with similar code so I've combined both to form this PR. 

There are three new functions `elbv2-target-groups`, `target-groups` and `target-group-instances`.
First function `elbv2-target-groups` takes a load balancer name and outputs target groups attached to the load balancer. Second function `target-groups` shows standalone target groups, and the last function `target-group-instances` takes target groups on the input and show EC2 instances behind them.

All functions support completion and can be combined with other functions in BMA way, e.g. `elbv2s mywebsite | elbv2-target-groups | target-group-instances`.

### CODE REVIEW

**Comment by mbailey** [comment]
Thanks Rastislav.

The code looks good and the commands look useful.

The only problem is, I need to test it and I'm not running the resources (elbv2, target-group, instances) to play with.

I do not currently have the time to spend creating this myself and as I've not been using elbv2's it would require an unknown amount of time.

Would you be able to include (under cloudformation/ dir) some cloudformation templates that create a stack containing:
- alb + target-group(s) + instances
- nlb + target-group(s) + instances

If you could do that, I'll fire them up in the bash-my-aws test account and have a play with the commands.

I think it is useful to have example cloudformation in the project for users to be able to explore and play with also.

What do you think?

**Comment by nitrocode** [comment]
I like this a lot!

```bash
$ target-group-instances atlantis
x.x.x.x  4141  healthy  atlantis

$ target-groups atlantis
atlantis  HTTP  4141  vpc-snip  ip  atlantis

$ target-groups
snip          HTTP   1     vpc-snip           ip        snip
snip          HTTP   80    vpc-snip           instance  snip
snip          HTTPS  8080  vpc-snip           instance  snip
snip          HTTP   8080  vpc-snip           instance  snip

$ elbv2-target-groups test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
snip  HTTP   80    vpc-snip  test
```

**Comment by barlik** [comment]
For cloudformation, I've found some sample templates provided by AWS at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html#w2ab1c35c58c13c23. All of them use application load balancer, however I've taken one of them and extended it to create both ALB and NLB load balancers. You can find a gist at https://gist.github.com/barlik/8aa84058ec3d93275fb895165972cf7b

> I think it is useful to have example cloudformation in the project for users to be able to explore and play with also.

Sounds like a good idea, I'll try to tidy up the template, remove all unessential parts and convert to YAML so it fits with the other templates in the repository. What do you think?
Meanwhile, you can test with the above gist, and/or with commands from the documentation shared by @nitrocode .

**Comment by barlik** [comment]
I've simplified the cloudformation template, converted to YAML, and added to the cloudformation directory.

**Comment by vazudevan** [comment]
Recently stumbled upon BMA and its part of my setup.  Thank you @mbailey for this utility. 

I was looking for target-group related functions and this pull request aptly suits, thanks to @barlik. 

Can the function `target-group-instances` rather named as `target-group-endpoints`.  The thought process is it is not mandatorily instances that are linked to target-groups they could be lambda, IP or instances.

Thoughts ?

**Comment by barlik** [comment]
I think that `target-group-endpoints` is fine, but there is no concept of endpoints in AWS documentation, so it might be a bit confusing.
The other good option would be `target-group-health` since that's the name of the underlying AWS cli command.

**Comment by mbailey** [comment]
> Recently stumbled upon BMA and its part of my setup. Thank you @mbailey for this utility.

Thanks! It's nice to hear.

**Comment by mbailey** [comment]
> Recently stumbled upon BMA and its part of my setup. Thank you @mbailey for this utility.

Thanks. I get notified when people star the repo but it's extra special when someone writes to say thanks. :-)

> Can the function `target-group-instances` rather named as `target-group-endpoints`. The thought process is, it is not mandatorily instances that are linked to target-groups. They could be lambda, IP or instances.
> 
> Thoughts ?


As barlik replied, targets can also be lambas (or IPs).

I think `target-group-targets` might be best? It's the term AWSCLI uses to refer to the targets in the output of describe-target-health.

thoughts?



```
          aws elbv2 describe-target-health \
              --target-group-arn arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/my-targets/73e2d6bc24d8a067

       Output:

          {
              "TargetHealthDescriptions": [
                  {
                      "HealthCheckPort": "80",
                      "Target": {
                          "Id": "i-ceddcd4d",
                          "Port": 80
                      },
                      "TargetHealth": {
                          "State": "healthy"
                      }
                  },
                  {
                      "HealthCheckPort": "80",
                      "Target": {
                          "Id": "i-0f76fade",
                          "Port": 80
                      },
                      "TargetHealth": {
                          "State": "healthy"
                      }
                  }
              ]
          }
```

**Comment by vazudevan** [comment]
Yes. `target-group-endpoints` sounds apt.

**Comment by barlik** [comment]
Function `target-group-instances` renamed to `target-group-targets`.

**Comment by mbailey** [comment]
Thanks, this is great.

**Pull request merged**
