### PR TITLE
Adds reset-password command to IAM functions

### PR DESCRIPTION
**Pull request by mostfunkyduck**
I would elaborate, but I think the name says it all :)
I'm just getting into this repo, so forgive me if I missed some conventions

### CODE REVIEW

**Comment by mbailey** [comment]
I've been mostly offline for the past few days.

Some thoughts on this one:
- for security reasons I'd prefer passwords are not echo'd to the terminal
- It would be good to be able to pipe in users from `iam-users` command added today #261.

What do you think about something like:

```
$ iam-users bill | iam-user-password-reset
Enter new password for user:billybob: *******
Confirm new password for user:billybob: ********
Require password reset on next sign-in? [Y/n]: 
Updated password for user:billybob

**Comment by mostfunkyduck** [comment]
Yeah, that's a good idea, I may not be able to get back to this for a couple of days, but @XaosTX is working on something similar and will probably have a better version up soon (we work together)

**Comment by XaosTX** [comment]
Just submitted https://github.com/bash-my-aws/bash-my-aws/pull/262 on similar topic.

**Comment by mostfunkyduck** [comment]
#264 does this better, closing.

**Pull request closed without merging**
